trigger:
  - develop
  - staging
  - qa
  - uat

pool:
  vmImage: ubuntu-latest

steps:
  #- task: NodeTool@0
  #  inputs:
  #    versionSpec: '14.17.6'
  #  displayName: 'Install Node.js'

  #- script: |
  #    npm install
  #    npm run build
  #  displayName: 'npm install and build'
  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: logeld_new_hos_backend
